CacheExpires: 1m
CheckAnchors: true
CheckDoctype: false
# This refers to actual <link> elements vvvv
CheckLinks: false
CheckMeta: false
CheckGeneric: false
CheckMailto: false
CheckTel: false
CheckMetaRefresh: false
LogLevel: 0
