name: build-docs

on:
  push:
    branches:
      - "**"
      - "!main"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  build-docs:
    # For internal PRs, this will run on `push` events;
    #   for external/forked PRs, it will run on `pull_request` events.
    #   Ideally we'd have checked this condition when defining the triggers,
    #   but that's not supported by GitHub actions.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      # - name: Verify format
      #   run: npm run format:check
      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Remove https redirect
        run: |
          sed -i '/SERVER_PORT/d;/SERVER_NAME/d' build/.htaccess
      - name: Run web server
        run: |
          docker run -d --name webserver -v "$PWD/build":/app -p 8888:8080 bitnami/apache:2.4.54
          echo "container_ip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' webserver)" >> $GITHUB_ENV
      - name: Download URLs from sitemap from production and make them look like an html page
        run: curl -sL https://docs.camunda.io/sitemap.xml | grep -oP '<loc>\K.*?(?=</loc>)' | sed "s!https://docs.camunda.io!http://${{ env.container_ip }}:8080!g" | sed "s/^.*$/\<a href=\"&\"\>link\<\/a>/g" > sitemap.prod.html
      - name: Make product links look like an html page
        run: grep 'https://docs.camunda.io' product-links.txt | sed "s!https://docs.camunda.io!http://${{ env.container_ip }}:8080!g" | sed "s/^.*$/\<a href=\"&\"\>link\<\/a>/g" > product-links.prod.html
      - name: Waiting for URL available
        uses: nev7n/wait_for_response@v1
        with:
          url: "http://${{ env.container_ip }}:8080/"
      - name: Validate sitemap links
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml
          path: sitemap.prod.html
      - name: Validate product links
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml
          path: product-links.prod.html
